rootProject.name = "Artifex"

include("plugin")
include("project:application")
include("project:common")
include("project:common-bridge")
include("project:common-bridge-bukkit")
include("project:common-bridge-bungee")
include("project:common-runtime")
include("project:controller")
include("project:implementation-bukkit")
include("project:implementation-bungee")
include("project:implementation-common-default")
include("project:implementation-common-project")
include("project:proxy-bukkit")
include("project:proxy-bungee")